// react-shop-result-strict-transitions/src/pages/result.tsx
import './result.css'
import { Provider } from 'react-redux'
import rootStore from '../store/transitionStore.ts'
import ProductList from '../components/ProductList'
import FilterList from '../components/FilterList'

export default function ResultPage() {
  return (
    <Provider store={rootStore}>
      <h1>Result page</h1>

      <main className="main-content">
        <FilterList />
        <ProductList />
      </main>
    </Provider>
  )
}

// vue-shop-result/src/pages/result.vue
<template>
  <h1>Result page</h1>
  <main class="main-content">
    <FilterList />
    <ProductList />
  </main>
</template>

<script setup lang="ts">
import FilterList from '../components/FilterList.vue'
import ProductList from '../components/ProductList.vue'
</script>

<style scoped>
.main-content {
  display: flex;
  gap: 30px;
}
</style>
