// react-shop-result/src/components/FilterList.tsx
import { ChangeEvent } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { selectProductTags } from '../store/productStore.ts'

export default function FilterList() {
  const tags = useSelector(selectProductTags)

  const dispatch = useDispatch()

  function updateSearchQuery(event: ChangeEvent<HTMLInputElement>): void {
    const input = event.target
    const query = input.value

    dispatch({
      type: 'filter/search',
      payload: query === '' ? null : query,
    })
  }

  function updateMaxPrice(event: ChangeEvent<HTMLInputElement>): void {
    const input = event.target
    const maxPrice = input.valueAsNumber

    dispatch({
      type: 'filter/maxPrice',
      payload: maxPrice,
    })
  }

  function updateMinRating(event: ChangeEvent<HTMLInputElement>): void {
    const input = event.target
    const minRating = input.valueAsNumber

    dispatch({
      type: 'filter/minRating',
      payload: minRating,
    })
  }

  function updateOnlyInStock(event: ChangeEvent<HTMLInputElement>): void {
    const input = event.target
    const onlyInStock = input.checked

    dispatch({
      type: 'filter/onlyInStock',
      payload: onlyInStock,
    })
  }

  let enabledTags: string[] = []

  function updateTags(event: ChangeEvent<HTMLInputElement>): void {
    const input = event.target
    const tagName = input.name

    if (enabledTags.includes(tagName)) {
      enabledTags = enabledTags.filter((tag) => tag !== tagName)
    } else {
      enabledTags.push(tagName)
    }

    dispatch({
      type: 'filter/tags',
      payload: enabledTags,
    })
  }

  return (
    <form>
      <input placeholder="Search" type="text" onChange={updateSearchQuery} />

      <input placeholder="max price" type="number" onChange={updateMaxPrice} />

      <input placeholder="min rating" type="number" min={0} max={5} onChange={updateMinRating} />

      <input id="onlyInStockCheckbox" type="checkbox" onChange={updateOnlyInStock} />
      <label form="onlyInStockCheckbox">only in stock</label>

      <div>
        {tags.map((tag) => (
          <div key={tag}>
            <input id={tag + 'checkbox'} type="checkbox" name={tag} onChange={updateTags} />
            <label form={tag + 'checkbox'}>{tag}</label>
          </div>
        ))}
      </div>
    </form>
  )
}

// vue-shop-result-strict-transitions/src/components/FilterList.vue
<template>
  <form>
    <input placeholder="search" type="text" v-model="searchQuery" @input="updateSearchQuery" />

    <input placeholder="max price" type="number" v-model="maxPrice" @input="updateMaxPrice" />

    <input placeholder="min rating" type="number" :min="0" :max="5" v-model="minRating" @input="updateMinRating" />

    <input id="onlyInStockCheckbox" type="checkbox" v-model="onlyInStock" @change="updateOnlyInStock" />
    <label for="onlyInStockCheckbox">only in stock</label>

    <div v-for="tag in productStore.tags" :key="tag">
      <input :id="tag + 'checkbox'" type="checkbox" :value="tag" v-model="enabledTags" @change="updateTags" />
      <label :for="tag + 'checkbox'">{{ tag }}</label>
    </div>
  </form>
</template>

<script setup lang="ts">
import { useFilterStore } from '../store/filterStore.ts'
import { useProductStore } from '../store/productStore.ts'
import { ref } from 'vue'

const filterStore = useFilterStore()
const productStore = useProductStore()

const searchQuery = ref<string | null>(filterStore.searchQuery)
const maxPrice = ref<number | string>(filterStore.maxPrice)
const minRating = ref<number | string>(filterStore.minRating)
const onlyInStock = ref<boolean>(filterStore.onlyInStock)
const enabledTags = ref<string[]>(filterStore.tags)

function updateSearchQuery(): void {
  filterStore.updateSearchQuery(searchQuery.value)
}

function updateMaxPrice(): void {
  filterStore.updateMaxPrice(maxPrice.value === '' ? Infinity : Number(maxPrice.value))
}

function updateMinRating(): void {
  filterStore.updateMinRating(minRating.value === '' ? -Infinity : Number(minRating.value))
}

function updateOnlyInStock(): void {
  filterStore.updateOnlyInStock(onlyInStock.value)
}

function updateTags(): void {
  filterStore.updateTags(enabledTags.value)
}
</script>
